name: Test Previews

on: 
  repository_dispatch:
    types:
      - resources-previewed
      - resources-unpreviewed
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Payload: $JSON"
      env: 
        JSON: ${{ toJson(github.event.client_payload) }} | tr -d '\n'
